### ISSUE TITLE
Crash in Django 3.1 on `pgmakemigrations` and `migrate`

### ISSUE THREAD

**Issue by askoretskiy** [SectorLabs/django-postgres-extra#111]
When using `pgmakemigrations` and `migrate` with Django 3.1.2 I get this error:

```
Traceback (most recent call last):
  File "src/manage.py", line 22, in <module>
    main()
  File "src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/psqlextra/management/commands/pgmakemigrations.py", line 11, in handle
    return super().handle(*app_labels, **options)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 164, in handle
    changes = autodetector.changes(
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/db/migrations/autodetector.py", line 129, in _detect_changes
    self.new_apps = self.to_state.apps
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/db/migrations/state.py", line 208, in apps
    return StateApps(self.real_apps, self.models)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/db/migrations/state.py", line 271, in __init__
    self.render_multiple([*models.values(), *self.real_models])
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/django/db/migrations/state.py", line 306, in render_multiple
    model.render(self)
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/psqlextra/backend/migrations/state/model.py", line 73, in render
    fields = {name: field.clone() for name, field in self.fields}
  File "/Users/artem/projects/social-connect/.venv/lib/python3.8/site-packages/psqlextra/backend/migrations/state/model.py", line 73, in <dictcomp>
    fields = {name: field.clone() for name, field in self.fields}
AttributeError: 'str' object has no attribute 'clone'
```

That code works with Django 3.0.

It seems the issue is that in Django 3.1 `self.fields` is no longer a list of tuples but rather a dict.

Here is a quick fix:
```patch
-        fields = {name: field.clone() for name, field in self.fields}
+        fields = self.fields.items() if isinstance(self.fields, dict) else self.fields
+        fields = {name: field.clone() for name, field in fields}
```

It feels like a show-stopper for me. I would prepare a pull request with this easy fix

**Comment by Photonios** [comment]
This was fixed in v2.0: https://pypi.org/project/django-postgres-extra/2.0/

**Comment by askoretskiy** [comment]
Thank you for release and merging the fix
